version: "3.8"
services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    restart: unless-stopped
